blueprint:
  name: Pilotage chauffage
  description: Gestion des différents modes de chauffage - Stop  Hors-gel  Auto confort Auto eco
  domain: automation
  source_url: https://github.com/tstelmaszyk/chauffage-home-assistant/blob/main/blueprint/chauffage_pilotage.yaml

  input:
    entity_consigne:
      name: Consigne
      description: Champs d'entrée de la température de consigne (input number).
      selector:
        entity:
          domain: climate
    temperature_hors_gel:
      name: Temperature hors gel
      description: Temparature de hors gel à parametrer (absence longue ou chauffage éteint)
      selector:
        number:
          min: 3
          max: 10
          step: 0.5
    temperature_eco:
      name: Temperature eco
      description: Temparature economie à choisir (nuit ou absence courte)
      selector:
        number:
          min: 10
          max: 21
          step: 0.5
    temperature_confort:
      name: Temperature de confort
      description: Temparature de confort à choisir
      selector:
        number:
          min: 15
          max: 28
          step: 0.5
    entity_activation:
      name: Activation ou non du chauffage
      description: Bouton switch à creer pour activer ou non le chauffage (été/hivers, arrêt long vacances ....)
      selector:
        entity:
          domain: input_boolean
    entity_precense:
      name: Precense ou non à la maison
      description: Switch pour indiquer ou non la précense dans le domicile
      selector:
        entity:
          domain: input_boolean
    entity_planning:
      name: Calendrier
      description: Horraire de chauffe
      selector:
        entity:
          domain: schedule

variables:
  temperature_hors_gel: !input temperature_hors_gel
  temperature_eco: !input temperature_eco
  temperature_confort: !input temperature_confort

alias: Pilotage chauffage
description: ''
trigger:
  - platform: state
    entity_id: !input entity_activation
  - platform: state
    entity_id: !input entity_precense
  - platform: state
    entity_id: !input entity_planning
action:
  - choose:
      # ----- Mode Hors-gel
      - conditions:
          - condition: state
            entity_id: !input entity_activation
            state: "off"
        sequence:
          - service: climate.set_temperature
            data:
              value: '{{temperature_hors_gel}}'
            target:
              entity_id: !input entity_consigne
      # ----- Mode absent
      - conditions:
          - condition: state
            entity_id: !input entity_precense
            state: "off"
        sequence:
          - service: climate.set_temperature
            data:
              value: '{{temperature_eco}}'
            target:
              entity_id: !input entity_consigne
      # ----- Mode Auto - confort
      - conditions:
          - condition: state
            entity_id: !input entity_planning
            state: "on"
        sequence:
          - service: climate.set_temperature
            data:
              value: '{{temperature_confort}}'
            target:
              entity_id: !input entity_consigne
      # ----- Mode Auto - eco
      - conditions:
          - condition: state
            entity_id: !input entity_planning
            state: "off"
        sequence:
          - service: climate.set_temperature
            data:
              value: '{{temperature_eco}}'
            target:
              entity_id: !input entity_consigne

mode: single
